import 'package:recipe_api/models/food.dart';

List<Recipe> listOfBreakfast = [
  Recipe(recipeCategory: 'Breakfast', recipeName: 'Avacado Toast', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 15.0, cookTime: 10.0, recipeServing: 2, recipeIngredients: ['1/2 small avocado', '1/2 teaspoon fresh lemon juice', 'salt', 'black pepper', '1 slice bread'], recipeMethod: ['In a small bowl, combine avocado, lemon juice, salt, and pepper. Gently mash with the back of a fork.', 'Top toasted bread with mashed avocado mixture. Drizzle with olive oil and sprinkle over desired toppings.'], recipeReview: 45),
  Recipe(recipeCategory: 'Breakfast', recipeName: 'Smoothie', recipeImage: 'https://images.pexels.com/photos/5366704/pexels-photo-5366704.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 5.0, cookTime: 0.0, recipeServing: 2, recipeIngredients: ['1/2 cup coconut water', '1 banana', '2 cups spinach', '1 cup frozen mango'], recipeMethod: ['In a blender, add ingredients in the order they are listed. Purée ingredients until smooth.'], recipeReview: 25),
  Recipe(recipeCategory: 'Breakfast', recipeName: 'Burritos', recipeImage: 'https://images.pexels.com/photos/5848051/pexels-photo-5848051.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 35.0, cookTime: 20.0, recipeServing: 8, recipeIngredients: ['3 tbsp vegetable oil', '4 cups frozen hash brown potatoes', '8 eggs', '1 can chopped green chillies', 'salt', 'pepper', '6 sausages', '8 tortillas'], recipeMethod: ['Oil and potatoes together over medium high heat.', 'In large bowl, beat eggs, green chiles, salt and pepper until well blended. In same skillet over medium-high heat, cook sausage 2 to 3 minutes, stirring frequently, until browned. Stir in egg mixture; cook 2 to 3 minutes, stirring occasionally, until scrambled.',  'To assemble burritos, spoon line of hash browns down center of each tortilla. Top with cheese and egg mixture.', 'Roll up each tortilla tightly to secure filling. Serve immediately.'], recipeReview: 155),
  Recipe(recipeCategory: 'Breakfast', recipeName: 'Omelette', recipeImage: 'https://images.pexels.com/photos/6294248/pexels-photo-6294248.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 2.0, cookTime: 4.0, recipeServing: 1, recipeIngredients: ['2 eggs', '20 tbsp water', 'salt', 'black pepper'], recipeMethod: ['Whisk eggs, water, salt and pepper.', 'When eggs are almost set on surface but still look moist, cover half of omelette with filling. Slip spatula under unfilled side; fold over onto filled half.', 'Cook for a minute, then slide omelette onto plate.'], recipeReview: 65),
  Recipe(recipeCategory: 'Breakfast', recipeName: 'Smoothie Bowl', recipeImage: 'https://images.unsplash.com/photo-1534352436920-f658b50b73fe?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=987&q=80', prepTime: 5.0, cookTime: 00.0, recipeServing: 2, recipeIngredients: ['1 banana, sliced and frozen', '1 cup frozen mango chunks', '1 cup frozen pineapple chunks', '1 cup almond milk'], recipeMethod: ['In blender, pulse banana, mango, and pineapple with almond milk until smooth but still thick, stopping and stirring occasionally. Add more liquid if needed. Pout into 2 bowls. Top as desired.'], recipeReview: 145),
];

List<Recipe> listOfLunch = [
  Recipe(recipeCategory: 'Lunch', recipeName: 'Mug Omelette', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 5.0, cookTime: 10.0, recipeServing: 1, recipeIngredients: ['2 eggs', '1/2 bell pepper', '2 slices ham', '1/4 cup Spinach', 'salt', 'pepper'], recipeMethod: ['Combine all ingredients in a microwaveable mug.', 'Cook for 2-3 minutes, making sure the egg doesn’t bubble over. Stir halfway through the cooking process.'], recipeReview: 15),
  Recipe(recipeCategory: 'Lunch', recipeName: 'Toastadas', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 15.0, cookTime: 10.0, recipeServing: 2, recipeIngredients: ['1 1/2 cups chopped cucumber', '1 cup chopped cherry tomatoes', '1/2 cup chopped green olives', '1/4 cup diced shallot', '1/4 cup chopped parsley', '1 tbsp olive oil', 'lemon juice', 'salt', 'pepper', 'tortillas', '1/2 cup hummus', 'salad'], recipeMethod: ['Prepare the salad. Add the cucumbers, tomatoes, olives, shallots and parsley into a mixing bowl. In a separate bowl whisk together dressing ingredients and pour over the salad. Toss to combine.', 'Make the tostadas. Toast the corn tortillas until golden brown and crispy. Top with a layer of hummus (I use about 2 tablespoons) and about 1/4 cup of the salad. Drizzle with tahini and enjoy!'], recipeReview: 45),
  Recipe(recipeCategory: 'Lunch', recipeName: 'Naan Pizza', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 5.0, cookTime: 5.0, recipeServing: 2, recipeIngredients: ['2 naans', 'Tomato sauce', 'Garlic powder', 'Italian seasoning', 'Sliced fresh mozzarella', 'Fresh basil', 'salt', 'pepper', 'olive oil'], recipeMethod: ['Place the naans on one larger or two smaller baking sheets. Spread each naan with an even layer of tomato sauce. Lightly sprinkle them with garlic powder and Italian seasoning. Add a few slices of mozzarella to each naan and fill in the gaps with the basil. Season with salt & pepper.', 'Broil for 5 minutes, or until the cheese is bubbly and the edges are lightly browned.', 'Add some more fresh basil (I like to tear it into smaller pieces) and a drizzle of olive oil to each pizza. Slice and serve immediately.'], recipeReview: 82),
  Recipe(recipeCategory: 'Lunch', recipeName: 'Tuna Salad', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 10.0, cookTime: 10.0, recipeServing: 4, recipeIngredients: ['2 cans tuna in water', '1/4 mayonnaise', '2 tbsp relish', '2 tbsp red onion', 'salt', 'pepper'], recipeMethod: ['Place drained tuna in a medium bowl.', 'Add the mayonnaise, relish, red onion and a little salt and pepper.', 'Stir with a fork until everything is well combined. Taste and add more salt and pepper as needed.'], recipeReview: 68),
  Recipe(recipeCategory: 'Lunch', recipeName: 'Chicken Salad', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 5.0, cookTime: 5.0, recipeServing: 2, recipeIngredients: ['1/2 cup mayonnaise', '1 tbps lemon juice', 'salt', 'black pepper', '2 cups chicken', '1 stalk celery', '1/2 cup almonds'], recipeMethod: ['Place almonds in a frying pan. Toast over medium-high heat, shaking frequently. Watch carefully, as they burn easily.', 'In a medium bowl, mix together mayonnaise, lemon juice, and pepper. Toss with chicken, almonds, and celery.'], recipeReview: 27),
];

List<Recipe> popularRecipes = [
  Recipe(recipeCategory: 'Popular', recipeName: 'Avacado Toast', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 15.0, cookTime: 10.0, recipeServing: 2, recipeIngredients: ['1/2 small avocado', '1/2 teaspoon fresh lemon juice', 'salt', 'black pepper', '1 slice bread'], recipeMethod: ['In a small bowl, combine avocado, lemon juice, salt, and pepper. Gently mash with the back of a fork.', 'Top toasted bread with mashed avocado mixture. Drizzle with olive oil and sprinkle over desired toppings.'], recipeReview: 45),
  Recipe(recipeCategory: 'Lunch', recipeName: 'Naan Pizza', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 5.0, cookTime: 5.0, recipeServing: 2, recipeIngredients: ['2 naans', 'Tomato sauce', 'Garlic powder', 'Italian seasoning', 'Sliced fresh mozzarella', 'Fresh basil', 'salt', 'pepper', 'olive oil'], recipeMethod: ['Place the naans on one larger or two smaller baking sheets. Spread each naan with an even layer of tomato sauce. Lightly sprinkle them with garlic powder and Italian seasoning. Add a few slices of mozzarella to each naan and fill in the gaps with the basil. Season with salt & pepper.', 'Broil for 5 minutes, or until the cheese is bubbly and the edges are lightly browned.', 'Add some more fresh basil (I like to tear it into smaller pieces) and a drizzle of olive oil to each pizza. Slice and serve immediately.'], recipeReview: 82),
  //Komin hingað
  Recipe(recipeCategory: 'Popular', recipeName: 'Avacado Toast', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 15.0, cookTime: 10.0, recipeServing: 2, recipeIngredients: ['1/2 small avocado', '1/2 teaspoon fresh lemon juice', 'salt', 'black pepper', '1 slice bread'], recipeMethod: ['In a small bowl, combine avocado, lemon juice, salt, and pepper. Gently mash with the back of a fork.', 'Top toasted bread with mashed avocado mixture. Drizzle with olive oil and sprinkle over desired toppings.'], recipeReview: 45),
  Recipe(recipeCategory: 'Popular', recipeName: 'Avacado Toast', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 15.0, cookTime: 10.0, recipeServing: 2, recipeIngredients: ['1/2 small avocado', '1/2 teaspoon fresh lemon juice', 'salt', 'black pepper', '1 slice bread'], recipeMethod: ['In a small bowl, combine avocado, lemon juice, salt, and pepper. Gently mash with the back of a fork.', 'Top toasted bread with mashed avocado mixture. Drizzle with olive oil and sprinkle over desired toppings.'], recipeReview: 45),
  Recipe(recipeCategory: 'Popular', recipeName: 'Avacado Toast', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 15.0, cookTime: 10.0, recipeServing: 2, recipeIngredients: ['1/2 small avocado', '1/2 teaspoon fresh lemon juice', 'salt', 'black pepper', '1 slice bread'], recipeMethod: ['In a small bowl, combine avocado, lemon juice, salt, and pepper. Gently mash with the back of a fork.', 'Top toasted bread with mashed avocado mixture. Drizzle with olive oil and sprinkle over desired toppings.'], recipeReview: 45),
];

