import 'package:recipe_app/models/food.dart';

List<Recipe> popularRecipes = [
  Recipe(recipeCategory: 'Popular', recipeName: 'Avacado Toast', recipeImage: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', prepTime: 15.0, cookTime: 10.0, recipeServing: 2, recipeIngredients: ['1/2 small avocado', '1/2 teaspoon fresh lemon juice', 'salt', 'black pepper', '1 slice bread'], recipeMethod: 'In a small bowl, combine avocado, lemon juice, salt, and pepper. Gently mash with the back of a fork. Top toasted bread with mashed avocado mixture. Drizzle with olive oil and sprinkle over desired toppings.', recipeReview: 45),
  Recipe(recipeCategory: 'Lunch', recipeName: 'Naan Pizza', recipeImage: 'https://images.pexels.com/photos/1260968/pexels-photo-1260968.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', prepTime: 5.0, cookTime: 5.0, recipeServing: 2, recipeIngredients: ['2 naans', 'Tomato sauce', 'Garlic powder', 'Italian seasoning', 'Sliced fresh mozzarella', 'Fresh basil', 'salt', 'pepper', 'olive oil'], recipeMethod: 'Place the naans on one larger or two smaller baking sheets. Spread each naan with an even layer of tomato sauce. Add a few slices of mozzarella to each naan and fill in the gaps with the basil.', recipeReview: 82),
  Recipe(recipeCategory: 'Dinner', recipeName: 'Broccoli Pasta', recipeImage: 'https://images.unsplash.com/photo-1607118750694-1469a22ef45d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=987&q=80', prepTime: 5.0, cookTime: 10.0, recipeServing: 2, recipeIngredients: ['4 oz. pasta', '0.33 lb. frozen broccoli florets ', '1 tbsp butter', '1 tbsp parmesan', 'salt', 'pepper'], recipeMethod: 'Bring a pot of water to a boil, then add the pasta. Boil until the pasta is al dente (7-10 minutes). Add the frozen broccoli florets to the boiling pasta water, turn off the heat, and let sit for 1-2 minutes, or until the broccoli is tender-crisp. Drain the pasta and broccoli in a colander. Transfer the pasta and broccoli back to the pot (with the heat off) or to a bowl and add the butter.', recipeReview: 82),
  Recipe(recipeCategory: 'Snack', recipeName: 'Apple Chips', recipeImage: 'https://images.pexels.com/photos/8963959/pexels-photo-8963959.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', prepTime: 15.0, cookTime: 180.0, recipeServing: 4, recipeIngredients: ['2 apples', '1/4 cup Italian dressing', '1/2 teaspoon ground cinnamon', '1 1/2 teaspoon sugar'], recipeMethod: 'Place the apple slices flat on a baking sheet, being careful not to overlap them. Sprinkle with cinnamon and sugar. Bake for 1 hour, flip the pieces over, bake for 1 more hour. Let cool in the oven for 1 hour.', recipeReview: 15),
  Recipe(recipeCategory: 'Desert', recipeName: 'Mousse', recipeImage: 'https://images.pexels.com/photos/1707920/pexels-photo-1707920.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', prepTime: 20.0, cookTime: 0.0, recipeServing: 2, recipeIngredients: ['1/4 cup chocolate chips', '1 tbsp water', '1 large egg yolk', '1/2 tbsp vanilla extract', '1/2 whipping cream', '1 tbsp sugar'], recipeMethod: 'In a small saucepan, melt chocolate chips with water; stir until smooth. Stir a small amount of hot chocolate mixture into egg yolk; return all to the pan, stirring constantly. Cook and stir for 2 minutes or until slightly thickened. Remove from the heat; stir in vanilla. Quickly transfer to a small bowl. Stir occasionally until completely cooled.', recipeReview: 84),
];
